version: '3'

services:
  master:
    image: locustio/locust:2.15.1
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://master:8089

  worker:
    image: locustio/locust:2.15.1
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master

  quark-app:
    build:
      context: ./../../../
      dockerfile: ./src/main/docker/Dockerfile.native-micro
    image: quark-app